### ISSUE TITLE
incompatible with python 3.8

### ISSUE THREAD

**Issue by tlaeven** [basnijholt/adaptive-scheduler#139]
Hey, I think this line is not compatible with python<3.9

https://github.com/basnijholt/adaptive-scheduler/blob/332432d8a5790871b890b1fa70f0a412d2196d69/adaptive_scheduler/utils.py#L676

**Comment by basnijholt** [comment]
That is fine because I changed it to ≥3.9: 
https://github.com/basnijholt/adaptive-scheduler/blob/2b930ecc789c7f08cd1ae68634ecad1a05bc1075/pyproject.toml#L8

However, tests in https://github.com/basnijholt/adaptive-scheduler/pull/141 show that there are failing tests for Python 3.9.

**Comment by basnijholt** [comment]
Made it Python 3.8 compatible in https://github.com/basnijholt/adaptive-scheduler/pull/142.
