### ISSUE TITLE
# of points is off

### ISSUE THREAD

**Issue by aeantipov** [basnijholt/adaptive-scheduler#223]
"# of points" is off.
This run had 386 total points. 
In the output I see
![image](https://github.com/basnijholt/adaptive-scheduler/assets/1170855/917d2ed5-2473-4332-950b-ef0adcd982e9)
Related: for average job start time I sometimes see something negative like "-1 d, 22 h, 2 m, 52 s"

@jbweston reporting it here.

**Comment by basnijholt** [comment]
That's a lot of points 😅

**Comment by aeantipov** [comment]
Must be some string concat? Or unlucky unsigned integer?

**Comment by aeantipov** [comment]
Here's more :D 
![image](https://github.com/basnijholt/adaptive-scheduler/assets/1170855/6899bed0-7daa-4448-8c3b-f6d8a812f858)
![image](https://github.com/basnijholt/adaptive-scheduler/assets/1170855/57c94cbd-dcb6-4c6f-8d75-5e07fa752bef)
It is "78651020278296845758863217029700770326221603779977640765871788973614310400613279426033698870017979734910185675666927119788269706313682564536717660171807007783766186738624689387730793896417908717971868125777164901018876449284104385721655477357951619758806534705063716382740761857326818795477710649162477972728878141012567695641720763976908934176827793691378315926775972541014165657039591866446700102316918625710167777987787170627277498535682889137518725159511022977126462684168709541600171536460694072827105664271997527701084397469714366816621101496787594676818639728383897215750870595409804173438202703972341029173468941792868628648688784257510755070047964669010433940059149056998482568155740476807612823510960908698497798868891666935993778087847992079219397719210482789877427927773186587595830365679396930081887596949581557806939311807833186568172670177081191584838218117769093875673831109592578120812697098679754710079810581741052573117808952081781178887341198080987955699511128753699848017848768058000113199533904490878753118988065120678637855772947276785974599266821411036119161129977151071910476461023311739809684648845853382818826712881828399784476448631744191098024832280107890101779095751373998030727170267777811011067814682057630881011721822512052889991377789828411988922388286747882082046675741071987643100369640846811086657076298335700895757364734782001072982817437633176967060859271798951865359442289110411111079271050875317149696010324790068647476629595947039794096411087773377774102968343978882578530622681628304111397306811575631108672731085175768847768777007221776610914843184237468763284717576737683307176750166199255795472638636726372346194735661797485833284237647963563568371731871109698738010173836183497385783273488349755175137945711370436354758979717597691683767348747084647117745483358350741679387151101339585834181587391840584028122930279406258743387447582820952467618911781387946866467629004832072227365872483758374836074308049" :)

**Comment by jgukelberger** [comment]
Finally ran into this, too. The underlying issue is that the `npoints` value is quoted in the log files. It's hence parsed as a string, triggering string concatenation upon summing. Here is an example line from a log file:
```
{"event": "current status", "elapsed_time": "1:17:04.244039", "overhead": 4.308440128469426, "npoints": "112", "npoints/s": 0.02422145328719723, [...]}
```

Digging further, I think the root cause is that our custom learner class implicitly returns `np.int64` numbers from its `npoints` property. While a direct `json.dumps` would immediately raise a TypeError for int64, structlog appears to "helpfully" mangle it into a string.

We'll fix the return type on our side of course, but it might also be a good idea to make the code here more robust - either by explicitly casting to `int` in `_get_log_entry` or by raising an error in `parse_log_files` when encountering a non-numeric type?

**Comment by aeantipov** [comment]
What a dig, thanks! Do you think the date issue has the same origin?

**Comment by jgukelberger** [comment]
> What a dig, thanks! Do you think the date issue has the same origin?

No, the datetime fields are already explicitly converted as far as I can see. Also I haven't personally encountered that issue. While for small negative start times I might conjecture a clock sync issue, a >1 day mismatch seems unlikely, so I really have no idea where that would come from.

**Comment by basnijholt** [comment]
I just opened https://github.com/basnijholt/adaptive-scheduler/pull/226
