### ISSUE TITLE
Make it harder to accidentally "cancel jobs"

### ISSUE THREAD

**Issue by jbweston** [basnijholt/adaptive-scheduler#46]
The "update info" and "cancel jobs" buttons are very close together in the interactive widget.

We could either increase the distance between the buttons, or require a confirmation before canceling jobs.

**Comment by basnijholt** [comment]
Good idea!

I guess we could have the cancel button split into two buttons that are `Confirm cancel` and `Don't cancel`.

**Comment by basnijholt** [comment]
Closed by b21f35e94db063131dc22aae94b308a83c6c7601.

**Comment by basnijholt** [comment]
![confirm-deny mov](https://user-images.githubusercontent.com/6897215/91167408-35e6e100-e6d4-11ea-8a9b-4f4ee710a366.gif)
