### ISSUE TITLE
Yellow text is difficult to read in jupyter lab

### ISSUE THREAD

**Issue by CameronKing** [basnijholt/adaptive-scheduler#47]
This is a quality of life issue, but it would be fantastic if the warning color for run metrics could be made a deeper shade of yellow. For example, the mean cpu usage is unreadable for me without using viewing angle tricks on my monitor:
![image](https://user-images.githubusercontent.com/3657359/86270269-d363df80-bb7f-11ea-9001-50ab3fa20474.png)

**Comment by basnijholt** [comment]
Fixed by https://github.com/basnijholt/adaptive-scheduler/pull/159 and https://github.com/basnijholt/adaptive-scheduler/pull/158
