### ISSUE TITLE
Unicode error on template writing

### ISSUE THREAD

**Issue by johnkgamble** [basnijholt/adaptive-scheduler#54]
I've been seeing some sporadic r/w issues with unicode. Difficult to reproduce, but it looks like modifying line 608 of `server_support.py` to:

    with open(run_script_fname, "w",encoding='utf-8') as f:
        f.write(template)

fixes some things, since `template` has a unicode character (left arrow). @basnijholt , any  objection to specifying the encoding?

**Comment by basnijholt** [comment]
@johnkgamble, I fixed this and released https://github.com/basnijholt/adaptive-scheduler/releases/tag/v0.9.3
