### ISSUE TITLE
UnicodeDecodeError in _make_default_run_script

### ISSUE THREAD

**Issue by jgukelberger** [basnijholt/adaptive-scheduler#59]
Similar to but distinct from #54. When trying to submit jobs I get a unicode error at the location where the `run_script.py.j2` template is opened:
https://github.com/basnijholt/adaptive-scheduler/blob/f5a820430b3dbd8a4610d530e0b8c2b5caaedcfd/adaptive_scheduler/server_support.py#L553
Passing `encoding='utf-8'` to `open` should fix this one, too.

**Comment by basnijholt** [comment]
Thanks @jgukelberger!

Fixed in 0.9.8.
